language: node_js
cache:
directories:
- node_modules
notifications:
email: false
branches:
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: cIW8A757YY+o6AXdRblPstRUzpxL90DSWWLxv1JvaA5MhSWny3t5C1T5jMU1oZ0i1Y+346lLxHyKHJ3tk2unpX2iyLErYZWtuy0VMzXe+LH92iK0EYrLLHuRq920xxQoQ5TVjiDIX0l09wbc0JuoN5N5ZO5WKW6MXDHRgt4SDlaxRZxCd67ZFgXe84xogCKiPM6RDuP1bGtQOW0UqcY8DAhy1nLwGMnv0mTI0x1YjluAyPGgEdYcXsZkTDwPinFF9Ie9a5IO9K7TjT9BwvsCiAaWIR5jkiHE2cNlQ4wvJwgLJZhaV59bmAoivKyMOAqwq4suGPWfwkgbE/TvgE7yDI9tz2iWjN0ntcJZuXaZaMzpGz13AyU5FJzA8rlBrqbodehOXcYwvFQj+yCXEdst5Pldx+RjOg6ZHZY8HMeQJynF/z1dJKK2visZNizaMIR0pm3nSRBLVIBliv68p5oXWDhKZ8xxopo98RwVvMMsO/EqUubcbNeIxZJMENnncUHyPQRxgQ7irc2YQx4HXtQfARJbKV/ZYMo/M+91uVeuKf7XNkOk65rPoV4zHy6VNbXop+lBqOpQwcaSKDQikAhuqcnLSzK87KPoWkZWp5j/cRzTAIIdwEP4WUNEIR23So7oiw31LPrOq7CHs3dt+17NZJ1bUJbUmJGMhu9V+RouodE=
